### ISSUE TITLE
AttributeError: 'LPCCondorJob' object has no attribute 'env_dict'

### ISSUE THREAD

**Issue by patrickbryant** [CoffeaTeam/lpcjobqueue#13]
Trying to migrate my condor implementation from work_queue which [doesn't play nice with LPC temp directories](https://github.com/cooperative-computing-lab/cctools/issues/2973). 

In the simple example the line 
```
cluster = LPCCondorCluster()
```
needs to be
```
cluster = LPCCondorCluster(shared_temp_directory='/tmp', worker_extra_args=['--worker-port 10000:10070', '--nanny-port 10070:10100', '--no-dashboard'], job_script_prologue=[]) 
```

My job starts waiting for workers and then I get a never ending loop of 
```
Singularity> python ZZ4b/nTupleAnalysis/scripts/coffea_lpcjobqueue.py
WARNING: GSI authentication is enabled by your security configuration! GSI will not work in future releases.
For details, see https://htcondor-wiki.cs.wisc.edu/index.cgi/wiki?p=PlanToReplaceGridCommunityToolkit
Waiting for at least one worker...
Task exception was never retrieved
future: <Task finished name='Task-46' coro=<_wrap_awaitable() done, defined at /opt/conda/lib/python3.8/asyncio/tasks.py:688> exception=AttributeError("'LPCCondorJob' object has no attribute 'env_dict'")>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/opt/conda/lib/python3.8/site-packages/distributed/deploy/spec.py", line 63, in _
    await self.start()
  File "/srv/.env/lib/python3.8/site-packages/lpcjobqueue/cluster.py", line 106, in start
    job = self.job_script()
  File "/srv/.env/lib/python3.8/site-packages/lpcjobqueue/cluster.py", line 87, in job_script
    quoted_environment = quote_environment(self.env_dict)
AttributeError: 'LPCCondorJob' object has no attribute 'env_dict'
2022-09-12 11:45:41,124 - tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fa7907636a0>>, <Task finished name='Task-45' coro=<SpecCluster._correct_state_internal() done, def
ined at /opt/conda/lib/python3.8/site-packages/distributed/deploy/spec.py:319> exception=AttributeError("'LPCCondorJob' object has no attribute 'env_dict'")>)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/conda/lib/python3.8/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/conda/lib/python3.8/site-packages/distributed/deploy/spec.py", line 358, in _correct_state_internal
    await w  # for tornado gen.coroutine support
  File "/opt/conda/lib/python3.8/site-packages/distributed/deploy/spec.py", line 63, in _
    await self.start()
  File "/srv/.env/lib/python3.8/site-packages/lpcjobqueue/cluster.py", line 106, in start
    job = self.job_script()
  File "/srv/.env/lib/python3.8/site-packages/lpcjobqueue/cluster.py", line 87, in job_script
    quoted_environment = quote_environment(self.env_dict)
AttributeError: 'LPCCondorJob' object has no attribute 'env_dict'
```

**Comment by patrickbryant** [comment]
Fixed with:
```
cluster = LPCCondorCluster(shared_temp_directory='/tmp')
```

```
pip install git+https://github.com/CoffeaTeam/lpcjobqueue.git@v0.2.6
```
