### ISSUE TITLE
ImportError when using a virtual environment

### ISSUE THREAD

**Issue by kapsiak** [CoffeaTeam/lpcjobqueue#27]
When launching dask workers on condor nodes around 50% of the time, the worker will fail to start with the error shown below, seeming to indicate some versioning mismatch. 
I cannot replicate this issue on an interactive node. 

This is using a  virtual environment on both the interactive and worker node, using the below package versions.
```
coffea: 2024.2.0
awkward: 2.6.1
dask-awkward: 2024.2.0
dask: 2024.1.1
```

The container being used is `/cvmfs/unpacked.cern.ch/registry.hub.docker.com/coffeateam/coffea-dask:latest-py3.10`.

The error in question:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/opt/conda/lib/python3.10/site-packages/distributed/__init__.py", line 23, in <module>
    from distributed.actor import Actor, ActorFuture, BaseActorFuture
  File "/opt/conda/lib/python3.10/site-packages/distributed/actor.py", line 13, in <module>
    from distributed.client import Future
  File "/opt/conda/lib/python3.10/site-packages/distributed/client.py", line 50, in <module>
    from distributed.core import ErrorMessage, OKMessage
  File "/opt/conda/lib/python3.10/site-packages/distributed/core.py", line 36, in <module>
    from distributed import profile, protocol
  File "/opt/conda/lib/python3.10/site-packages/distributed/protocol/__init__.py", line 6, in <module>
    from distributed.protocol.core import decompress, dumps, loads, maybe_compress, msgpack
  File "/opt/conda/lib/python3.10/site-packages/distributed/protocol/core.py", line 9, in <module>
    from distributed.protocol import pickle
  File "/opt/conda/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 11, in <module>
    from distributed.protocol.serialize import dask_deserialize, dask_serialize
  File "/opt/conda/lib/python3.10/site-packages/distributed/protocol/serialize.py", line 16, in <module>
    from dask.sizeof import sizeof
  File "/opt/conda/lib/python3.10/site-packages/dask/sizeof.py", line 276, in <module>
    _register_entry_point_plugins()
  File "/opt/conda/lib/python3.10/site-packages/dask/sizeof.py", line 267, in _register_entry_point_plugins
    registrar = entry_point.load()
  File "/opt/conda/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 209, in load
    module = import_module(match.group('module'))
  File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/srv/coffeaenv/lib/python3.10/site-packages/dask_histogram/__init__.py", line 3, in <module>
    import boost_histogram.axis as _axis
  File "/opt/conda/lib/python3.10/site-packages/boost_histogram/__init__.py", line 3, in <module>
    from . import accumulators, axis, numpy, storage
  File "/opt/conda/lib/python3.10/site-packages/boost_histogram/accumulators.py", line 3, in <module>
    from ._core.accumulators import (  # pylint: disable=import-error
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/conda/lib/python3.10/site-packages/boost_histogram/_core.cpython-310-x86_64-li
nux-gnu.so)
```

As a note, this is not using `ship_env=True`, but rather a slight variation that compresses the environment before shipping, but which ultimately accomplishes the same thing. I have verified that the interactive and worker nodes are in the same image, and are using the same environment with the same package versions.

**Comment by nsmith-** [comment]
Can you see if the error still exists with newer images, e.g. `coffeateam/coffea-base-almalinux8:0.7.22-py3.10`
cc @cmoore24-24

**Comment by kapsiak** [comment]
This seems to have resolved the issue! Thank you.
